"""Provider boundary — the only seam Stockbit is allowed to cross."""

from __future__ import annotations

from collections.abc import AsyncIterator
from datetime import date
from typing import Any, Protocol

from app.domain.models import Book, Candle, KeyStats, Mover, Quote, Resolution, Symbol, Trade


class LiveFeed(Protocol):
    """Push feed — Stockbit WSS in prod, fake in tests."""

    async def subscribe(self, symbols: set[Symbol], kinds: set[str] = ...) -> None: ...
    async def unsubscribe(self, symbols: set[Symbol]) -> None: ...
    def events(self) -> AsyncIterator[Trade | Quote | Book]: ...
    def snapshot_quotes(self) -> dict[Symbol, Quote]: ...
    def snapshot_books(self) -> dict[Symbol, Book]: ...
    def snapshot_trades(self, symbol: Symbol | None = None, limit: int = 100) -> list[Trade]: ...


class MarketDataProvider(Protocol):
    def live_feed(self) -> LiveFeed: ...

    def candles(
        self, symbol: Symbol, frm: date, to: date, resolution: Resolution
    ) -> AsyncIterator[Candle]: ...
    async def key_stats(self, symbol: Symbol) -> KeyStats: ...
    async def movers(self, kind: str, boards: list[str] | None = None) -> list[Mover]: ...
    async def broker_summary(
        self, symbol: Symbol, frm: str | None = None, to: str | None = None
    ) -> Any: ...
    async def brokers_top(self, frm: str, to: str) -> Any: ...
    async def brokers_top_stocks(self, frm: str, to: str) -> Any: ...
    async def broker_activity(self, code: str, frm: str, to: str) -> Any: ...
    async def sector_list(self) -> Any: ...
    async def subsectors(self, sid: str) -> Any: ...
    async def sector_companies(self, sid: str, sub_id: str) -> Any: ...
    async def seasonality(self, symbol: Symbol, year: int, back_year: int = 5) -> Any: ...
    async def fetch(
        self, url: str, params: dict[str, Any] | None = None, label: str = "fetch"
    ) -> Any: ...
